-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 16:04:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Contato` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Ano` YEAR NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Clientes_idClientes`),
  INDEX `fk_Veiculo_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `NomedaEquipe` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idMecanico`, `Equipe_idEquipe`),
  INDEX `fk_Mecanico_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdemServicoOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdemServicoOS` (
  `idOrdemServicoOS` INT NOT NULL AUTO_INCREMENT,
  `NumeroOS` VARCHAR(45) NULL,
  `DataEmissao` VARCHAR(45) NULL,
  `DataConclusao` VARCHAR(45) NULL,
  `ValorTotal` DECIMAL NULL,
  `Status` VARCHAR(45) NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idOrdemServicoOS`, `Veiculo_idVeiculo`, `Equipe_idEquipe`),
  INDEX `fk_OrdemServiçoOS_Veiculo1_idx` (`Veiculo_idVeiculo` ASC) VISIBLE,
  INDEX `fk_OrdemServiçoOS_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServiçoOS_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServiçoOS_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL AUTO_INCREMENT,
  `NomeServico` VARCHAR(45) NULL,
  `ValorMaodeObra` DECIMAL NULL,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OSServicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OSServicos` (
  `Serviço_idServico` INT NOT NULL,
  `OrdemServiçoOS_idOrdemServiçoOS` INT NOT NULL,
  PRIMARY KEY (`Serviço_idServico`, `OrdemServiçoOS_idOrdemServiçoOS`),
  INDEX `fk_Serviço_has_OrdemServiçoOS_OrdemServiçoOS1_idx` (`OrdemServiçoOS_idOrdemServiçoOS` ASC) VISIBLE,
  INDEX `fk_Serviço_has_OrdemServiçoOS_Serviço1_idx` (`Serviço_idServico` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_has_OrdemServiçoOS_Serviço1`
    FOREIGN KEY (`Serviço_idServico`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviço_has_OrdemServiçoOS_OrdemServiçoOS1`
    FOREIGN KEY (`OrdemServiçoOS_idOrdemServiçoOS`)
    REFERENCES `mydb`.`OrdemServicoOS` (`idOrdemServicoOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pecas` (
  `idPecas` INT NOT NULL AUTO_INCREMENT,
  `NomePeca` VARCHAR(45) NULL,
  `ValorUnitario` DECIMAL NULL,
  PRIMARY KEY (`idPecas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OSPecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OSPecas` (
  `OrdemServicoOS_idOrdemServicoOS` INT NOT NULL,
  `Pecas_idPecas` INT NOT NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`OrdemServicoOS_idOrdemServicoOS`, `Pecas_idPecas`),
  INDEX `fk_OrdemServicoOS_has_Pecas_Pecas1_idx` (`Pecas_idPecas` ASC) VISIBLE,
  INDEX `fk_OrdemServicoOS_has_Pecas_OrdemServicoOS1_idx` (`OrdemServicoOS_idOrdemServicoOS` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServicoOS_has_Pecas_OrdemServicoOS1`
    FOREIGN KEY (`OrdemServicoOS_idOrdemServicoOS`)
    REFERENCES `mydb`.`OrdemServicoOS` (`idOrdemServicoOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServicoOS_has_Pecas_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `mydb`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
